#

[DEFAULT]

RootFileDirectory = '/dartfs-hpc/rc/home/v/f007h9v/neutrals/resolvedvelocities/src/neutralwinds/ProcessingCode/output'

[PROCESSING]

NW_MinAltitude = 80.0
NW_MaxAltitude = 150.0
NW_DeltaAltitude = 5.0
LP_MinAltitude = 200.0
LP_MaxAltitude = 400.0
Elevation_Min = 50.0
Elevation_Max = 90.0
Azimuth_Min = -180.0
Azimuth_Max = 180.0
LocalTimeZone = -8.0
TestAlgorithm = False
dVLOSScaler = 10



[VVELS]
Velocity_ModelCovariance = [9e6,9e6,9e2]
Velocity_MaxAltitude = 1e6
Velocity_MinAltitude = 0.
FracErrorOffset = 200.
FracErrorThreshold = 0.5
AbsoluteErrorThreshold = 100.

[INVERTWINDS]

AbsoluteErrorFilter = 100.
Wind_ModelCovariance = [1.e6,1.e6,25.]
Efield_ModelCovariance = [10e-1,10e-1,1.e-5]

[GEOPHYSICALPARAMETERS]

Path2Data = 'GeophysicalParameters/Data/'
Path2MagFiles = '../MagFiles/'
KP_AP_File = 'KP_AP_F107_2006_2017.pkl'
DelayTime = 2
ByPass = True

[FILTERING]
FitCodeMin = 1
FitCodeMax = 4
Chi2Min = 0.1
Chi2Max = 10
