# THIS CONFIG HANDLES ALL THE BASIC CONFIGURATION OPTIONS

[DEFAULT]
path: /path/to/some/dir



[SECTION]
str = testing
strliteral = "blahblahblah/blah"
strliteralwithcomma: "This is just a message, nothing more."
commaseparatedlist: test1,test2,test3,test4
list = [3,2,1]
listoflists = [[1,2,3,4], [5,6,7,8],[9,10,11,12]]
dict = {"hello": 1}
nesteddict = {"level1": {"level2": {"level3": "end"}}}
tuple = (1,1)
tuplelist= [(1,1),(1,2)]
tupleoftuples = ((1,1),(1,2))
path2: /some/other/path
outpath: %(path)s/output
outpath2: %(path2)s/output
numbered_dict : {1:"test",2:"test2"}

[DB]
paths: db/test.db
tables: ['table1','table2']
columns: ['test1 text UNIQUE', 'test2 bool', 'test3 integer']


